settings:
  monitoring_debugging:
    label: Monitoring & Debugging
    items:
      data-persistence:
        label: Data Persistence
        get_cmd: [bash, -c, "if [[ -e /oem/.debug ]]; then echo Enabled; else echo Disabled; fi"]
        options:
          Enabled:
            label: Enabled
            cmd: [touch, /oem/.debug]
          Disabled:
            label: Disabled
            cmd: [rm, -f, /oem/.debug]
        default: Disabled
