on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - .github/workflows/*.yaml
  workflow_dispatch:

jobs:
  custom-firmware-build:
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: recursive

    - name: Load values vars.mk
      run: cat vars.mk >> "$GITHUB_ENV"

    - name: Restore Firmwares Cache
      id: cache-firmwares
      uses: actions/cache/restore@v4
      with:
        path: firmware/
        key: firmwares-${{ runner.os }}-${{ runner.arch }}-${{ env.FIRMWARE_VERSION }}

    - name: Restore Kernel Cache
      id: cache-kernel
      uses: actions/cache/restore@v4
      with:
        path: tmp/kernel/
        key: kernels-${{ runner.os }}-${{ runner.arch }}-${{ env.KERNEL_SHA }}

    - name: Install build dependencies
      run: |
        sudo apt-get update -y &&
        sudo apt-get install -y build-essential cmake \
          gcc-aarch64-linux-gnu pkg-config squashfs-tools git-core \
          bc libssl-dev

    - name: Set GIT_VERSION
      shell: bash
      run: |
        nextVer=$(./scripts/next_version.sh paxx12)
        echo "GIT_VERSION=${nextVer//v/}" | tee -a $GITHUB_ENV

    - name: Download firmware
      run: make firmware

    - name: Build with Basic firmware
      run: sudo make build PROFILE=basic OUTPUT_FILE=U1_basic_${{ env.GIT_VERSION }}_upgrade.bin

    - name: Build with Extended firmware
      run: sudo make build PROFILE=extended OUTPUT_FILE=U1_extended_${{ env.GIT_VERSION }}_upgrade.bin

    - name: Clear Kernel Git Repo
      run: sudo git -C tmp/kernel/ clean -fdx

    - name: Generate Changelog
      run: make changelog >> RELEASE.md

    - name: 'Release debian files'
      uses: ncipollo/release-action@v1
      with:
        tag: "v${{ env.GIT_VERSION }}"
        allowUpdates: false
        updateOnlyUnreleased: true
        prerelease: true
        bodyFile: RELEASE.md
        artifacts: "U1_*.bin"

    - name: Save Firmwares Cache
      if: steps.cache-firmwares.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: firmware/
        key: firmwares-${{ runner.os }}-${{ runner.arch }}-${{ env.FIRMWARE_VERSION }}

    - name: Save Kernel Cache
      if: steps.cache-kernel.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: tmp/kernel/
        key: kernels-${{ runner.os }}-${{ runner.arch }}-${{ env.KERNEL_SHA }}
